### ISSUE TITLE
Link's error

### ISSUE THREAD

**Issue by anassamii** [AkashRajpurohit/Spell-IT#7]
Hello, this link doesn't work anymore :

https://mock-server-akash.vercel.app/api/spell-it/level/$levelName

**Comment by AkashRajpurohit** [comment]
Hey, thanks for pointing this out, it is definitely moved to a different location, will update this soon.

**Comment by AkashRajpurohit** [comment]
This has been fixed in the release: https://github.com/AkashRajpurohit/Spell-IT/releases/tag/v1.1.0
