### ISSUE TITLE
No 'Access-Control-Allow-Origin' header

### ISSUE THREAD

**Issue by anassamii** [AkashRajpurohit/Spell-IT#8]
Hello, thanks for replying.

I still get this error :

Access to XMLHttpRequest at 'https://ms.akashrajpurohit.com/api/spell-it/level/Easy' from origin 'http://localhost:57465' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.

It is a backend's problem.

**Comment by AkashRajpurohit** [comment]
Hey, I think this should work fine already on the app, are you trying to hit the API endpoint directly?
If yes then may I ask the use-case around this?

**Comment by AkashRajpurohit** [comment]
Are you running the app but testing out locally or facing the issue in the released version of the app?

**Comment by AkashRajpurohit** [comment]
I have enabled CORS for this route, it should work now hopefully!

**Comment by anassamii** [comment]
Awesome, it worked !
Thank you :)

Le jeu. 2 jui. 2022 à 17:32, Akash Rajpurohit ***@***.***> a
écrit :
